export const INCREMENT_ACTIVE_STEP = "INCREMENT_ACTIVE_STEP";
export const RESET_ACTIVE_STEP = "RESET_ACTIVE_STEP";

export const LOAD_PRODUCTS = "LOAD_PRODUCTS";
export const SET_PRODUCTS = "SET_PRODUCTS";
